# Generated by Django 4.1.5 on 2023-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True, verbose_name="зарегистрирован"
                    ),
                ),
                (
                    "id_telegram",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="id пользователя в телеграмм",
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="никнейм")),
                ("name", models.CharField(max_length=100, verbose_name="имя")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="электронная почта"),
                ),
            ],
            options={
                "verbose_name": "Зарегистрированный пользователь",
                "verbose_name_plural": "Зарегистрированные пользователи",
                "ordering": ("-created_at",),
            },
        ),
    ]
