# Generated by Django 4.2 on 2023-04-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminTelegramBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_telegram",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="id администратора в телеграмм",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="не заполнено",
                        max_length=100,
                        null=True,
                        verbose_name="никнейм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Администратор бота",
                "verbose_name_plural": "Администраторы бота",
            },
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="зарегистрирован"),
        ),
    ]
