# Generated by Django 4.2 on 2023-04-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0002_admintelegrambot_alter_telegramuser_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstCategoryBottom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название кнопки"
                    ),
                ),
            ],
        ),
    ]
