# Generated by Django 4.2 on 2023-04-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0005_alter_firstcategorybottom_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstcategorybottom",
            name="descriptions",
            field=models.TextField(default="exit", verbose_name="описание кнопки"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="finalmessage",
            name="descriptions",
            field=models.TextField(verbose_name="сообщение"),
        ),
        migrations.CreateModel(
            name="ImageFirstCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image_bottom/first_category",
                        verbose_name="изображение к кнопки",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tg_bot.firstcategorybottom",
                        verbose_name="родительская кнопка",
                    ),
                ),
            ],
        ),
    ]
