# Generated by Django 4.2 on 2023-04-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0006_firstcategorybottom_descriptions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstcategorybottom",
            name="amount_photos",
            field=models.IntegerField(default=0, verbose_name="количество фотографий"),
        ),
    ]
