# Generated by Django 4.2 on 2023-04-27 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0007_firstcategorybottom_amount_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstcategorybottom",
            name="amount_photos",
        ),
    ]
