# Generated by Django 4.2 on 2023-04-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0008_remove_firstcategorybottom_amount_photos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagefirstcategory",
            options={
                "verbose_name": "Изображение первой категории",
                "verbose_name_plural": "Изображения первой категории",
            },
        ),
        migrations.CreateModel(
            name="ImageTwoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image_bottom/two_category",
                        verbose_name="изображение к кнопки",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tg_bot.twocategorybottom",
                        verbose_name="родительская кнопка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение второй категории",
                "verbose_name_plural": "Изображения второй категории",
            },
        ),
    ]
