# Generated by Django 4.2 on 2023-04-27 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0009_alter_imagefirstcategory_options_imagetwocategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twocategorybottom",
            name="image",
        ),
    ]
