# Generated by Django 4.2 on 2023-04-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0010_remove_twocategorybottom_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageThreeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="massage_image/",
                        verbose_name="изображение к сообщению",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение к 3 категории кнопок",
                "verbose_name_plural": "Изображения к 3 категории кнопок",
            },
        ),
        migrations.CreateModel(
            name="MessageThreeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptions", models.TextField(verbose_name="описание")),
                (
                    "ship_from",
                    models.DateField(blank=True, null=True, verbose_name="отправка с"),
                ),
                (
                    "ship_to",
                    models.DateField(blank=True, null=True, verbose_name="отправка до"),
                ),
                (
                    "lifetime",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="пожизненно"
                    ),
                ),
                (
                    "season",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="сезон"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение к 3 категории кнопок",
                "verbose_name_plural": "Сообщения к 3 категории кнопок",
            },
        ),
        migrations.RemoveField(
            model_name="threecategorybottom",
            name="descriptions",
        ),
        migrations.RemoveField(
            model_name="threecategorybottom",
            name="image",
        ),
        migrations.AlterField(
            model_name="imagefirstcategory",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tg_bot.firstcategorybottom",
                verbose_name="родительская кнопка",
            ),
        ),
        migrations.AlterField(
            model_name="imagetwocategory",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tg_bot.twocategorybottom",
                verbose_name="родительская кнопка",
            ),
        ),
        migrations.AlterField(
            model_name="threecategorybottom",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tg_bot.twocategorybottom",
                verbose_name="родительская кнопка",
            ),
        ),
        migrations.AlterField(
            model_name="twocategorybottom",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tg_bot.firstcategorybottom",
                verbose_name="родительская кнопка",
            ),
        ),
        migrations.DeleteModel(
            name="FinalMessage",
        ),
        migrations.AddField(
            model_name="messagethreecategory",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tg_bot.threecategorybottom",
                verbose_name="родительская кнопка",
            ),
        ),
        migrations.AddField(
            model_name="imagethreecategory",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tg_bot.messagethreecategory",
                verbose_name="сообщение",
            ),
        ),
    ]
