# Generated by Django 4.2 on 2023-04-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0011_imagethreecategory_messagethreecategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="сообщение")),
            ],
            options={
                "verbose_name": "Сообщение об ошибке ввода",
                "verbose_name_plural": "Сообщение об ошибке ввода",
            },
        ),
        migrations.CreateModel(
            name="WelcomeMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="сообщение")),
            ],
            options={
                "verbose_name": "Приветственное сообщение",
                "verbose_name_plural": "Приветственное сообщение",
            },
        ),
    ]
