# Generated by Django 4.2 on 2023-04-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0013_alter_imagethreecategory_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressBottomFirstCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(default=0, verbose_name="количество нажатий"),
                ),
                (
                    "bottom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tg_bot.firstcategorybottom",
                        verbose_name="кнопка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tg_bot.telegramuser",
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
    ]
