# Generated by Django 4.2 on 2023-04-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0017_alter_pressbottombackandexitfirstcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admintelegrambot",
            options={
                "verbose_name": "5. Администратор бота",
                "verbose_name_plural": "5. Администраторы бота",
            },
        ),
        migrations.AlterModelOptions(
            name="errormessage",
            options={
                "verbose_name": "7. Сообщение об ошибке ввода",
                "verbose_name_plural": "7. Сообщение об ошибке ввода",
            },
        ),
        migrations.AlterModelOptions(
            name="firstcategorybottom",
            options={
                "verbose_name": "2. Первая категория кнопок",
                "verbose_name_plural": "2. Первая категория кнопок",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramuser",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "1. Зарегистрированный пользователь",
                "verbose_name_plural": "1. Зарегистрированные пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="threecategorybottom",
            options={
                "verbose_name": "4. Третья категория кнопок",
                "verbose_name_plural": "4. Третья категория кнопок",
            },
        ),
        migrations.AlterModelOptions(
            name="twocategorybottom",
            options={
                "verbose_name": "3. Вторая категория кнопок",
                "verbose_name_plural": "3. Вторая категория кнопок",
            },
        ),
        migrations.AlterModelOptions(
            name="welcomemessage",
            options={
                "verbose_name": "6. Приветственное сообщение",
                "verbose_name_plural": "6. Приветственное сообщение",
            },
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="зарегистрирован"
            ),
        ),
    ]
