# Generated by Django 4.2 on 2023-04-30 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0018_alter_admintelegrambot_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileThreeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to="file/three_category",
                        verbose_name="документы к сообщению",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tg_bot.messagethreecategory",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ к 3 категории кнопок",
                "verbose_name_plural": "Документы к 3 категории кнопок",
            },
        ),
    ]
